name: 2025 everyday read and recite

on:
  workflow_dispatch:
#  schedule:
#    - scron: '40 15 * * *'

jobs:
  create_html:
    runs-on: ubuntu-22.04
    
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: define_variable
        run: |
          git pull origin develop
          date_uni=$(date -d '4day' +%Y-%m-%d)
          content_recite=$(cat 2025schedule/everydayRecite.csv | grep ${date_uni} | awk -F, '{print $3}')
          content_readNS=$(cat 2025schedule/readNotSort.csv | grep ${date_uni} | sed -e 's/`//g' | awk -F, '$2!="完成" {print $2$3"章"$4} $2=="完成" {print $2$3" "$4}')
          content_readS=$(cat 2025schedule/readSort.csv | grep ${date_uni} | awk -F, '{print $2}')
          echo "${date_uni} ${content_recite} ${content_readNS} ${content_readS}" > checkerror.txt

      - name: write_variable_into_html
        run: |
          sed -e "26c ${date_uni}" template.html | sed -e "29c ${content_readNS}" > 1.html
          sed -e "38c ${date_uni}" 1.html | sed -e "41c ${content_readS}" > 2.html
          sed -e "13c ${date_uni}" 2.html | sed -e "16c ${content_recite}" > test.html
#        continue-on-error: true

      - name: delete_temp_file
        run: |
          rm -f {1..2}.html

      - name: push_to_repository
        run: |
          git config --global user.name "zextmayamaya"
          git config --global user.email "mayamaya@live.cn"
          git add .
          git commit -m "update ${date_uni} content"
          git push origin develop
