name: everyday-recite

on:
  workflow_dispatch:
#  schedule:
#    - cron: '0 16 * * *'

jobs:
  create_html:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: node.js
        uses: actions/setup-node@v4
      - name: pull files
        run: |
          git pull
          ls -lh

