name: everyday-recite

on:
  workflow_dispatch:
#  schedule:
#    - cron: '0 16 * * *'

jobs:
  create_html:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: node.js
        uses: actions/setup-node@v4
      - name: shell create file
        run: |
          day=$(date --date="1day" +%F)
          content=$(cat everydayRecite.csv | grep ${day} | cut -d ',' -f 3)
          cat template.html | sed -e "12c $day" | sed -e "15c $content" > index.html
          pwd;ls -lh
      - name: pull files
        run: |
          npm i --no-fund
          git pull
          node app.js
          git add .
          git commit -m "update index.html"
          git status
          git push origin develop
