name: test_read_file_schedule
on:
  push:
  workflow-dispatch:
  schedule:
    # - cron: '*/2 * 14-15 6 2024'
jobs:
  job01:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: read-file
        run: |
          echo "hello "+date > file
  job02:
    runs-on: ubuntu-latest
    needs: [job01]
    steps:
      - name: run multi lines
        run: |
          ps -ef | grep $(date +%F)
          hostname -I
