name: everyday-recite

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10,16 * * *'

jobs:
  create_html:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: shell create file
        run: |
          git pull
          day=$(date --date="1day" +%F)
          content=$(cat everydayRecite.csv | grep ${day} | cut -d ',' -f 3)
          dayNoSort=$(date +%-m月%-d日 -d "1day")
          contentNoSort=$(cat readNotSort | grep ${dayNoSort} | awk -F, '$2!="任务完成" {print $2" "$3"章 "$4}')
          cat template.html | sed -e "12c $day" | sed -e "15c $content" | sed -e "21c $dayNoSort" |
          sed -e "24c $contentNoSort" > index.html
      - name: add schedule B
        run: |
          daySort=$(date --date="1day" +%Y/%-m/%-d)
          contentSort=$(cat readSort | grep ${daySort} | cut -d ',' -f 2)
          cat -n index.html
          cat index.html | sed -e "30c $daySort" | sed -e "33c $contentSort" > index1.html
          rm index.html
          mv index1.html index.html
          echo 'DATE=$(cat index.html | sed -n "30p")' >> $GITHUB_ENV
      - name: pull files
        if: env.DATE == $(date --date="1day" +%Y/%-m/%-d)
        run: echo "ok"
#        run: |
#          git config --global user.email "mayamaya@live.cn"
#          git config --global user.name "zextmayamaya"
#          git add .
#          git commit -m "update index.html"
#          git status
#          git push origin develop -f
