# 测试每天能否定时执行任务
name: everyday-morning-greet

on:
  schedule:
    - cron: '10 0 * * *'
  workflow_dispatch:

jobs:
  timezone_date:
    runs-on: [ubuntu-latest]
    steps:
      - name: everyday morning greet
        run: echo "hello everyday 8:10"
      - name: show date
        run: date +%F_%H:%M
