# 测试每天能否定时执行任务
name: test

on:
  workflow_dispatch:

env:
  username: "zextmayamaya"
jobs:
  timezone_date:
    runs-on: [ubuntu-latest]
    steps:
      - name: show env
        run: $username
      - name: show date
        run: date +%F_%H:%M
