# 测试每天能否定时执行任务
name: test

on:
  workflow_dispatch:

env:
  username: "zextmayamaya"
jobs:
  test_env:
    runs-on: [ubuntu-latest]
    
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: show env
        run: $username
      - name: show date
        run: date +%F_%H:%M
